
  try {

    let x = Promise.reject(400);

  } catch (err) {

    console.log(err);

  }




